module rmw_dds_common {

  module msg {
    const long MAX_NAME_LENGTH = 256;
    const long MAX_NAMESPACE_LENGTH = 256;

    struct Gid {
      octet data[24];
    };

    struct NodeEntitiesInfo {
      string<MAX_NAMESPACE_LENGTH> node_namespace;
      string<MAX_NAME_LENGTH> node_name;
      sequence<Gid> reader_gid_seq;
      sequence<Gid> writer_gid_seq;
    };

    struct ParticipantEntitiesInfo {
      Gid gid;
      sequence<NodeEntitiesInfo> node_entities_info_seq;
    };
  };

};
